apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: fmdatabasestatefulset
spec:
  serviceName: fmdatabaseservice
  replicas: 1
  selector:
    matchLabels:
      role: fmmongolabel
  template:
    metadata:
      labels:
        role: fmmongolabel
        replicaSet: MainRepSet
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: replicaSet
                      operator: In
                      values:
                        - MainRepSet
                topologyKey: kubernetes.io/hostname
      terminationGracePeriodSeconds: 10
      containers:
        - name: fmdatabasecontainer
          image: mongo
          command:
            - "mongod"
            - "--wiredTigerCacheSizeGB"
            - "0.1"
            - "--bind_ip"
            - "0.0.0.0"
            - "--replSet"
            - "MainRepSet"
          resources:
            requests:
              cpu: 0.2
              memory: 200Mi
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: fmdatabasevolumeclaim
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: fmdatabasevolumeclaim
        annotations:
          volume.beta.kubernetes.io/storage-class: "standard"
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi